apiVersion: v1
kind: Service
metadata:
  name: cloudp-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32001
  selector:
    app: cloudp
  type: NodePort