apiVersion: v1
kind: Pod
metadata:
  name: cloudp
  labels:
    run: cloudp
    
spec:
  containers:
  - image: sayali063/cloudp
    name: cloudp
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always