apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
data:
  application.yml: |
    logging:
      level:
        root: INFO
        com.example.myapp: DEBUG
    metrics:
      enabled: true
      endpoint: /actuator/prometheus
      scrapeInterval: 30s
  stackdriver.yml: |
    spring:
      cloud:
        gcp:
          logging:
            enabled: true
          monitoring:
            enabled: true
